# Generated by Django 5.0.2 on 2024-05-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='rating',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
