# Generated by Django 5.0.2 on 2024-05-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_alter_novel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='features',
            field=models.CharField(blank=True, choices=[('hot', 'Hot'), ('new', 'New'), ('full', 'Full')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(blank=True, choices=[('continue', 'tiếp tục'), ('stoped', 'Đã dừng lại'), ('complete', 'Hoàn thành')], max_length=200, null=True),
        ),
    ]
