# Generated by Django 5.0.2 on 2024-05-07 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_alter_chaptercontent_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
