# Generated by Django 5.0.2 on 2024-05-09 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ')], max_length=200, null=True),
        ),
    ]
